version: "3.9"
services:
  frente-node:
    build: .
    container_name: frente-delivery-pkg-node
    command: npm run start:dev
    depends_on: 
      - frente-postgres
    ports:
      - "3000:3000"
    volumes: 
      - .:/frente-delivery-pkg
    networks: 
      - app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    working_dir: /frente-delivery-pkg
  frente-postgres:
    image: postgres
    container_name: frente-delivery-pkg-postgres
    volumes: 
      - frente-postgres-data:/data
    ports:
      - "5432:5432"
    networks: 
      - app
    env_file:
      - .env
volumes:
  frente-postgres-data:
networks: 
  app:
    name: app