version: "3.9"
services:
  node:
    image: node
    container_name: frente-delivery-pkg-node
    command: npm run debug
    depends_on: 
      - postgres
    ports:
      - "3000:3000"
    volumes: 
      - .:/project
    networks: 
      - app
    environment:
      - POSTGRES_HOSTNAME=postgres
    working_dir: /project
  postgres:
    image: postgres
    container_name: frente-delivery-pkg-postgres
    volumes: 
      - frente-postgres-data:/data
    ports:
      - "5432:5432"
    networks: 
      - app
    environment:
      - POSTGRES_USER=frente-pkg
      - POSTGRES_PASSWORD=frente123
      - POSTGRES_HOSTNAME=postgres
volumes:
  frente-postgres-data:
networks: 
  app:
    name: app